"""Add registration fields to User

Revision ID: 2854c7eb0f1e
Revises: 7077b2b08be1
Create Date: 2025-12-16 17:12:18.504680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2854c7eb0f1e'
down_revision = '7077b2b08be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('selfie_filename', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('dni_photo_filename', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dni_photo_filename')
        batch_op.drop_column('selfie_filename')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
