"""Add expenses_description and net_benefits to GovernmentFund

Revision ID: 526cb63ab816
Revises: a9a6297f03e8
Create Date: 2025-12-29 02:05:01.868341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526cb63ab816'
down_revision = 'a9a6297f03e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('government_fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expenses_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('net_benefits', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('government_fund', schema=None) as batch_op:
        batch_op.drop_column('net_benefits')
        batch_op.drop_column('expenses_description')

    # ### end Alembic commands ###
