"""Add lottery models

Revision ID: 67baee144504
Revises: 12030b7cba9c
Create Date: 2025-12-17 17:04:17.270829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67baee144504'
down_revision = '12030b7cba9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lottery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_jackpot', sa.Float(), nullable=True),
    sa.Column('last_run_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lottery_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.String(length=5), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lottery_ticket')
    op.drop_table('lottery')
    # ### end Alembic commands ###
