"""Add discord_id, salary_account_number, GovernmentFund fields

Revision ID: a9b72f6218ce
Revises: e21c5876eb37
Create Date: 2025-12-29 02:32:39.128244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b72f6218ce'
down_revision = 'e21c5876eb37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('government_fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expenses_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('net_benefits', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('salary_account_number', sa.String(length=20), nullable=True))
        batch_op.drop_index('ix_user_dni')
        batch_op.create_index(batch_op.f('ix_user_dni'), ['dni'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dni'))
        batch_op.create_index('ix_user_dni', ['dni'], unique=1)
        batch_op.drop_column('salary_account_number')
        batch_op.drop_column('discord_id')

    with op.batch_alter_table('government_fund', schema=None) as batch_op:
        batch_op.drop_column('net_benefits')
        batch_op.drop_column('expenses_description')

    # ### end Alembic commands ###
