"""Add official fields to User

Revision ID: bc266b03a824
Revises: 2854c7eb0f1e
Create Date: 2025-12-16 18:31:58.339682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc266b03a824'
down_revision = '2854c7eb0f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('official_rank', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('official_status', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_badge_id'), ['badge_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badge_id'))
        batch_op.drop_column('official_status')
        batch_op.drop_column('official_rank')
        batch_op.drop_column('department')
        batch_op.drop_column('badge_id')

    # ### end Alembic commands ###
